#!/bin/bash
# Setup script for Personal Finance Tracker
# This script configures the project for building with Flutter

set -e

echo "========================================"
echo " Personal Finance Tracker - Setup"
echo "========================================"

# Path to Flutter SDK (modify if needed)
FLUTTER_PATH="${FLUTTER_PATH:-/Users/arun/Downloads/flutter}"
FLUTTER_BIN="$FLUTTER_PATH/bin/flutter"

# Check if Flutter exists
if [ ! -f "$FLUTTER_BIN" ]; then
    echo "❌ Flutter not found at: $FLUTTER_PATH"
    echo "   Set the FLUTTER_PATH environment variable to your Flutter SDK path."
    echo "   Example: FLUTTER_PATH=/path/to/flutter ./setup.sh"
    exit 1
fi

echo "✅ Found Flutter at: $FLUTTER_PATH"

# Get the absolute path of the project directory
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROJECT_DIR"

echo ""
echo "📦 Running flutter pub get..."
"$FLUTTER_BIN" pub get

echo ""
echo "📝 Updating local.properties..."
mkdir -p android
cat > android/local.properties << EOF
# Auto-generated by setup.sh
flutter.sdk=$FLUTTER_PATH
flutter.versionCode=1
flutter.versionName=1.0.0
EOF
echo "   ✅ local.properties updated"

echo ""
echo "========================================"
echo " ✅ Setup complete!"
echo "========================================"
echo ""
echo " Next steps:"
echo "  1. Configure Google Cloud Console (see README.md)"
echo "  2. Run the app:"
echo "     $FLUTTER_BIN run"
echo ""
echo "  For Android APK:"
echo "     $FLUTTER_BIN build apk --debug"
echo ""